Цель работы: научиться работать с датасетами.А так же реализовать базовый анализ датасета. Вывести весь датасет и описать его.Вывести размерноть массива.Вывести наименование всех колонок, написать что они означают.
Вывести все уникальные значения. Отсортировать по определенным параметрам. Удалить ненужные столбцы или строчки. Заменить определенные значения в датасете.Удалить дубликаты.Провести анализ с помощью функций info.
Провести анализ с помощью функций describe.Провести выборку данных по строкам и столбцам с помощью loc. Сохранить новый датасет.

In [1]:
import pandas as pd
import numpy as np

games = pd.read_csv("games.csv")
games

id  rated    created_at  last_move_at  turns victory_status  \
0      TZJHLljE  False  1.504210e+12  1.504210e+12     13      outoftime   
1      l1NXvwaE   True  1.504130e+12  1.504130e+12     16         resign   
2      mIICvQHh   True  1.504130e+12  1.504130e+12     61           mate   
3      kWKvrqYL   True  1.504110e+12  1.504110e+12     61           mate   
4      9tXo1AUZ   True  1.504030e+12  1.504030e+12     95           mate   
...         ...    ...           ...           ...    ...            ...   
20053  EfqH7VVH   True  1.499791e+12  1.499791e+12     24         resign   
20054  WSJDhbPl   True  1.499698e+12  1.499699e+12     82           mate   
20055  yrAas0Kj   True  1.499698e+12  1.499698e+12     35           mate   
20056  b0v4tRyF   True  1.499696e+12  1.499697e+12    109         resign   
20057  N8G2JHGG   True  1.499643e+12  1.499644e+12     78           mate   

      winner increment_code       white_id  white_rating            black_id  \
0      white           15+2       bourgris          1500                a-00   
1      black           5+10           a-00          1322           skinnerua   
2      white           5+10         ischia          1496                a-00   
3      white           20+0  daniamurashov          1439        adivanov2009   
4      white           30+3      nik221107          1523        adivanov2009   
...      ...            ...            ...           ...                 ...   
20053  white          10+10        belcolt          1691            jamboger   
20054  black           10+0       jamboger          1233  farrukhasomiddinov   
20055  white           10+0       jamboger          1219        schaaksmurf3   
20056  white           10+0   marcodisogno          1360            jamboger   
20057  black           10+0       jamboger          1235               ffbob   

       black_rating                                              moves  \
0              1191  d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...   
1              1261  d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...   
2              1500  e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...   
3              1454  d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...   
4              1469  e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...   
...             ...                                                ...   
20053          1220  d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...   
20054          1196  d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...   
20055          1286  d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...   
20056          1227  e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...   
20057          1339  d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...   

      opening_eco                            opening_name  opening_ply  
0             D10        Slav Defense: Exchange Variation            5  
1             B00  Nimzowitsch Defense: Kennedy Variation            4  
2             C20   King's Pawn Game: Leonardis Variation            3  
3             D02  Queen's Pawn Game: Zukertort Variation            3  
4             C41                        Philidor Defense            5  
...           ...                                     ...          ...  
20053         A80                           Dutch Defense            2  
20054         A41                            Queen's Pawn            2  
20055         D00         Queen's Pawn Game: Mason Attack            3  
20056         B07                            Pirc Defense            4  
20057         D00         Queen's Pawn Game: Mason Attack            3  

[20058 rows x 16 columns]

Пункт 1.Вывод датасета и его описание.
Это набор состоит из чуть более 20 000 шахматных партий, собранных от избранных пользователей на сайте Lichess.org. 
Для каждой из этих отдельных игр от Lichess. Эти данные  собраны с помощью Lichess API, который позволяет собирать историю игр любого пользователя. На Lichess есть несколько команд с более чем 1500 игроками,  это эффективный способ привлечь пользователей к коллекционированию игр.

In [23]:
games.shape

(20058, 16)

Пункт 2.Размерноть массива количество строк 20058 и столбцов 16.

In [5]:
games.columns

Index(['id', 'rated', 'created_at', 'last_move_at', 'turns', 'victory_status',
       'winner', 'increment_code', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_eco', 'opening_name', 'opening_ply'],
      dtype='object')

Пункт 3.Вывод наименования всех колонок, написать их значения.
Этот набор содержит:
Идентификатор игры;
Номинальный (Т/Ф);
Время начала;
Время окончания;
Количество ходов;
Статус игры;
Победитель;
Приращение времени;
Белый идентификатор игрока;
Рейтинг белого игрока;
Черный идентификатор игрока;
Рейтинг черных игроков;
Все ходы в стандартной шахматной записи;
Открытие Eco (стандартный код для любого открытия, перечислите здесь);
Начальное имя;
Открытие Ply (количество ходов в начальной фазе)

In [7]:
games["id"].unique()

array(['TZJHLljE', 'l1NXvwaE', 'mIICvQHh', ..., 'yrAas0Kj', 'b0v4tRyF',
       'N8G2JHGG'], dtype=object)

In [8]:
games["rated"].unique()

array([False,  True])

In [9]:
games["created_at"].unique()

array([1.50421000e+12, 1.50413000e+12, 1.50411000e+12, ...,
       1.49969788e+12, 1.49969613e+12, 1.49964315e+12])

In [10]:
games["last_move_at"].unique()

array([1.50421000e+12, 1.50413000e+12, 1.50411000e+12, ...,
       1.49969805e+12, 1.49969707e+12, 1.49964389e+12])

In [11]:
games["turns"].unique()

array([ 13,  16,  61,  95,   5,  33,   9,  66, 119,  39,  38,  60,  31,
        43,  52, 101,  25,  14,   3,  17,  36,  69,  54,  53,  64,  21,
        11,  19,  28,  22,  37,  34,  32,  71,  30,  41,  49,   7,  35,
         8,  44,  29,  40,  57,  78,  62,  87,  50, 131,  48,  47,  51,
        58, 114,  20,  85, 113,  75, 135,  81,  46,  70,  91, 137,  18,
       111,  90,  59,  26,  23, 118, 120,  24,   2,  97,  12,  72, 156,
        77,  65,  73, 125,  76,  63, 107, 100,  80, 105, 144, 158, 117,
       110, 178, 136, 124,  96,  10, 106,  15,  42, 159,  74, 112, 104,
       150,  88,  55, 103, 177,  82,  99,  67,   6, 115,  83,  89, 116,
        27, 102,  45,  98, 108,  92,  56, 123, 129,   4, 163, 130, 121,
        94,  79, 148, 195, 122, 128,  84,  86,  93, 161, 133,  68, 153,
       154, 160, 141, 132, 204, 140, 168, 127, 109, 174, 157, 142, 143,
       170,   1, 138, 171, 145, 151, 179, 149, 173, 208, 139, 134, 169,
       155, 164, 147, 126, 146, 190, 167, 255, 210, 176, 172, 18

In [12]:
games["victory_status"].unique()

array(['outoftime', 'resign', 'mate', 'draw'], dtype=object)

In [13]:
games["winner"].unique()

array(['white', 'black', 'draw'], dtype=object)

In [14]:
games["increment_code"].unique()

array(['15+2', '5+10', '20+0', '30+3', '10+0', '15+30', '15+0', '20+60',
       '5+40', '8+0', '15+15', '15+16', '11+0', '30+60', '15+5', '10+10',
       '15+3', '18+0', '30+30', '20+25', '5+5', '30+0', '40+40', '16+0',
       '6+10', '8+10', '8+12', '7+12', '15+10', '20+5', '20+10', '45+0',
       '5+8', '30+2', '25+0', '10+2', '7+2', '25+25', '7+8', '6+6',
       '10+4', '12+0', '15+1', '2+10', '9+0', '10+9', '6+7', '30+10',
       '30+15', '10+3', '45+30', '9+2', '7+3', '6+5', '25+5', '5+7',
       '8+2', '20+8', '30+5', '25+15', '15+7', '8+8', '5+9', '16+7',
       '10+7', '7+5', '40+20', '10+5', '11+5', '10+15', '180+0', '17+5',
       '8+5', '3+8', '60+120', '90+120', '15+8', '9+1', '9+3', '2+15',
       '10+1', '5+12', '60+10', '5+60', '8+15', '30+25', '12+1', '14+0',
       '60+20', '10+8', '20+3', '14+12', '7+7', '60+0', '45+45', '4+15',
       '5+6', '180+180', '8+3', '4+6', '10+25', '3+10', '7+4', '6+3',
       '5+15', '45+15', '15+20', '6+8', '6+9', '14+8', '6+4', '15+4',
 

In [15]:
games["white_id"].unique()

array(['bourgris', 'a-00', 'ischia', ..., 'samael88', 'belcolt',
       'marcodisogno'], dtype=object)

In [16]:
games["white_rating"].unique()

array([1500, 1322, 1496, ...,  860,  929,  880], dtype=int64)

In [17]:
games["black_id"].unique()

array(['a-00', 'skinnerua', 'adivanov2009', ..., 'farrukhasomiddinov',
       'schaaksmurf3', 'ffbob'], dtype=object)

In [18]:
games["black_rating"].unique()

array([1191, 1261, 1500, ...,  840,  857,  860], dtype=int64)

In [19]:
games["moves"].unique()

array(['d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5 Bf4',
       'd4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6 Qe5+ Nxe5 c4 Bb4+',
       'e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc6 bxc6 Ra6 Nc4 a4 c3 a3 Nxa3 Rxa3 Rxa3 c4 dxc4 d5 cxd5 Qxd5 exd5 Be6 Ra8+ Ke7 Bc5+ Kf6 Bxf8 Kg6 Bxg7 Kxg7 dxe6 Kh6 exf7 Nf6 Rxh8 Nh5 Bxh5 Kg5 Rxh7 Kf5 Qf3+ Ke6 Bg4+ Kd6 Rh6+ Kc5 Qe3+ Kb5 c4+ Kb4 Qc3+ Ka4 Bd1#',
       ...,
       'd4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd2 b6 Ne5 Nxe5 Bxe5 Nd7 Bxh7+ Kxh7 Qh5+ Kg8 Nf3 f6 Bf4 g5 Qg6+ Kh8 Nh4 Qe8 Qh6+ Kg8 Ng6 Kf7 Qh7#',
       'e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb6 c5 Nd5 Bc4 e6 Bxd5 exd5 Nc3 d4 Ne4 Bf5 f3 Nd7 b4 Nxe5 Bf4 f6 g4 Bxe4 fxe4 c6 Bxe5 fxe5 Nf3 Be7 Nxe5 Bf6 Nc4 O-O-O h4 h6 e5 b5 cxb6 Be7 bxa7 Kc7 a3 Rhf8 Kd2 Rf4 Rag1 d3 h5 Rf2+ Ke3 Re2+ Kf4 Rf8+ Kg3 Re3+ Nxe3 d2 Rd1 Bg5 Nf5 Kb7 Rhf1 Kxa7 Nd6 Rxf1 Rxf1 Kb6 e6 Kc7 Nf5 Kc8 e7 Kd7 a4 Bxe7 Nxe7 Kxe7 a5 Kd7 Rd1 Kc7 Rxd2 Kb7 Ra2 Ka6 Kf4 Kb5 a6 Kb6 a7 Kb5 a8=Q Kxb4 Qxc6 g5+ hxg6 Kb3 Rc

In [20]:
games["opening_eco"].unique()

array(['D10', 'B00', 'C20', 'D02', 'C41', 'B27', 'D00', 'C50', 'B01',
       'A00', 'C02', 'C00', 'C57', 'C55', 'A40', 'B20', 'A25', 'B21',
       'D01', 'C45', 'D06', 'B52', 'D20', 'B06', 'A45', 'B77', 'A21',
       'B70', 'B23', 'B76', 'C21', 'A80', 'A20', 'A04', 'C26', 'C44',
       'E10', 'A41', 'C01', 'A10', 'C18', 'A47', 'C10', 'D80', 'D30',
       'D41', 'A46', 'D31', 'C64', 'C24', 'A43', 'A08', 'B03', 'B29',
       'B02', 'B13', 'B57', 'E20', 'E11', 'C40', 'C11', 'C28', 'B30',
       'A56', 'C65', 'B90', 'B50', 'B51', 'E00', 'C70', 'B11', 'B22',
       'B40', 'B31', 'B18', 'C61', 'C78', 'B10', 'C22', 'C54', 'C68',
       'B12', 'C77', 'A42', 'C42', 'D07', 'B32', 'A22', 'C46', 'B07',
       'A06', 'C60', 'A07', 'A02', 'C58', 'A03', 'B54', 'D03', 'C69',
       'A31', 'D46', 'C34', 'C48', 'C47', 'B24', 'C67', 'E61', 'C53',
       'C23', 'B96', 'A05', 'D92', 'A49', 'C37', 'A09', 'A01', 'C88',
       'B34', 'C03', 'C33', 'A48', 'A11', 'A81', 'B05', 'B53', 'B08',
       'C30', 'A15',

In [21]:
games["opening_name"].unique()

array(['Slav Defense: Exchange Variation',
       'Nimzowitsch Defense: Kennedy Variation',
       "King's Pawn Game: Leonardis Variation", ...,
       "Queen's Indian Defense: Classical Variation |  Traditional Variation",
       "Queen's Gambit Declined: Slav |  Dutch Variation",
       'Sicilian Defense: Najdorf Variation |  Polugaevsky Variation'],
      dtype=object)

In [22]:
games["opening_ply"].unique()

array([ 5,  4,  3, 10,  6,  1,  9,  2,  8,  7, 17, 11, 12, 13, 18, 19, 15,
       16, 14, 28, 20, 22, 24], dtype=int64)

Пункт 4.Вывести все уникальные значения. Вывод производтся по каждому столбцу отдельно.

In [24]:
games.sort_values(by='turns')

id  rated    created_at  last_move_at  turns victory_status  \
4828   Z1M9z44Z   True  1.472750e+12  1.472750e+12      1         resign   
1946   3K5kYPO8   True  1.491530e+12  1.491530e+12      1         resign   
4115   3NQKJmJ5  False  1.500760e+12  1.500760e+12      1      outoftime   
13557  01dkNQ2O  False  1.504442e+12  1.504442e+12      1      outoftime   
13560  LAFV9u5Q  False  1.504442e+12  1.504442e+12      1      outoftime   
...         ...    ...           ...           ...    ...            ...   
16645  5ZjOnwjl   True  1.480271e+12  1.480272e+12    226           draw   
4236   vQq60Hur   True  1.474480e+12  1.474490e+12    255           draw   
16386  cZiGllu7   True  1.481753e+12  1.481755e+12    259           draw   
11554  pN0ioHNr   True  1.503084e+12  1.503086e+12    349      outoftime   
13859  pN0ioHNr   True  1.503084e+12  1.503086e+12    349      outoftime   

      winner increment_code      white_id  white_rating       black_id  \
4828   white           10+0        bert-w          1670     andreschil   
1946   black           10+0  serik-astana          1464     brorael357   
4115   white           5+15     fairygirl          2404  oreo_or_orion   
13557  white          20+10    jerusseust          2438     palermagno   
13560  white          20+10    jerusseust          2438      castlebit   
...      ...            ...           ...           ...            ...   
16645   draw           10+0       chunnev          1817      jhonthoth   
4236    draw            7+2       manipin          1585  kasparovd0311   
16386   draw           15+5      aragon26          1441      lone-wolf   
11554  white           10+0        shiwen          2194          kijek   
13859  white           10+0        shiwen          2194          kijek   

       black_rating                                              moves  \
4828           1175                                                 e4   
1946           1355                                                 g3   
4115           1616                                                 e4   
13557          1666                                                 e4   
13560          1885                                                 e4   
...             ...                                                ...   
16645          1907  e4 e6 Nf3 d5 exd5 exd5 d4 Nf6 Bg5 Be7 Nc3 Be6 ...   
4236           1448  e4 e6 Nc3 d5 exd5 exd5 d4 Nf6 Bf4 Be7 Nf3 O-O ...   
16386          1461  d4 d5 c4 c6 Nc3 Nf6 Bg5 Nbd7 Qc2 Qb6 e3 h6 Bf4...   
11554          2240  d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 Bg5 h6 Bxf6 Qxf6 Qb...   
13859          2240  d4 d5 c4 c6 Nf3 Nf6 Nc3 e6 Bg5 h6 Bxf6 Qxf6 Qb...   

      opening_eco                                 opening_name  opening_ply  
4828          B00                                  King's Pawn            1  
1946          A00                            Hungarian Opening            1  
4115          B00                                  King's Pawn            1  
13557         B00                                  King's Pawn            1  
13560         B00                                  King's Pawn            1  
...           ...                                          ...          ...  
16645         C00             French Defense: Knight Variation            3  
4236          C00               French Defense: Queen's Knight            3  
16386         D10                              Slav Defense #2            5  
11554         D30  Queen's Gambit Declined: Hastings Variation           13  
13859         D30  Queen's Gambit Declined: Hastings Variation           13  

[20058 rows x 16 columns]

Пункт 5.Сортировка в таблице по количеству ходов в партии в порядке возрастания.

In [31]:
games.sort_values(by='black_rating',ascending=False)



id  rated    created_at  last_move_at  turns victory_status  \
4473   rAO6oybn  False  1.480830e+12  1.480830e+12      1      outoftime   
12080  tgePSMBk  False  1.500474e+12  1.500476e+12     58         resign   
12680  0C3HN9UQ  False  1.496967e+12  1.496967e+12     22         resign   
12614  uH1mpzvB  False  1.500726e+12  1.500726e+12     17         resign   
12615  2qndM9O7  False  1.500415e+12  1.500417e+12    104         resign   
...         ...    ...           ...           ...    ...            ...   
2891   Ls7pzvc7   True  1.486680e+12  1.486680e+12     60           mate   
2328   FJZ23eFz  False  1.501010e+12  1.501010e+12     77           mate   
15380  FJZ23eFz  False  1.501013e+12  1.501014e+12     77           mate   
930    WRNkn1iH   True  1.498720e+12  1.498720e+12     74         resign   
11465  516BT5yk   True  1.501445e+12  1.501446e+12    120         resign   

      winner increment_code          white_id  white_rating          black_id  \
4473   white            5+5      ranchowangdu          1500        justicebot   
12080  black          10+20          dinobzik          1214         lance5500   
12680  black           15+0       raulelbueno          1384         lance5500   
12614  black          10+25       koryakinrus          1715         lance5500   
12615  black          10+15       koryakinrus          1715         lance5500   
...      ...            ...               ...           ...               ...   
2891   black           15+0     businessman47          1160       epicchess66   
2328   white            5+8     hash_13-chess          1128  christinebitonti   
15380  white            5+8     hash_13-chess          1128  christinebitonti   
930    black          14+12          mccheese           989          hortense   
11465  black           10+0  martinlutherking          1450   crazyscientist1   

       black_rating                                              moves  \
4473           2723                                                 e4   
12080          2621  e4 c5 Nf3 d6 d4 Nf6 Nc3 cxd4 Nxd4 Nc6 Nxc6 bxc...   
12680          2621  f3 e5 g3 d5 Bg2 Nf6 b3 Be7 Na3 O-O Bb2 Nc6 Bc3...   
12614          2621  e4 c5 Nf3 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Ng...   
12615          2621  e4 c5 Nf3 d6 d4 Nf6 e5 dxe5 Nxe5 Qxd4 Qxd4 cxd...   
...             ...                                                ...   
2891            796  e4 d5 exd5 Qxd5 Qf3 Qxf3 Nxf3 f5 Na3 h6 Nb5 Na...   
2328            795  g3 Nf6 Bg2 Nc6 Nf3 Ng4 O-O Na5 Nc3 e6 h3 Nh6 d...   
15380           795  g3 Nf6 Bg2 Nc6 Nf3 Ng4 O-O Na5 Nc3 e6 h3 Nh6 d...   
930             791  d4 d5 e4 dxe4 Bf4 Be6 Bb5+ Bd7 Nc3 Bxb5 Nxb5 e...   
11465           789  e4 c5 f4 d6 g4 Nf6 g5 Nxe4 d3 Qa5+ c3 Nxg5 fxg...   

      opening_eco                                       opening_name  \
4473          B00                                        King's Pawn   
12080         B56              Sicilian Defense: Classical Variation   
12680         A00                                   Gedult's Opening   
12614         B50  Sicilian Defense: Modern Variations |  Anti-Qx...   
12615         B50  Sicilian Defense: Modern Variations |  Anti-Qx...   
...           ...                                                ...   
2891          B01      Scandinavian Defense: Mieses-Kotroc Variation   
2328          A00                  Hungarian Opening: Indian Defense   
15380         A00                  Hungarian Opening: Indian Defense   
930           D00                             Blackmar-Diemer Gambit   
11465         B21                 Sicilian Defense: McDonnell Attack   

       opening_ply  
4473             1  
12080           10  
12680            1  
12614            6  
12615            6  
...            ...  
2891             4  
2328             2  
15380            2  
930              3  
11465            3  

[20058 rows x 16 columns]

Сортировка по рейтингу черных игроков в порядке убывания.

In [43]:
games.drop([1,2], axis=0, inplace=True)
games.drop([3,4], axis=0, inplace=True)
games

id  rated    created_at  last_move_at  turns victory_status  \
0      TZJHLljE  False  1.504210e+12  1.504210e+12     13      outoftime   
5      MsoDV9wj  False  1.504240e+12  1.504240e+12      5           draw   
6      qwU9rasv   True  1.504230e+12  1.504230e+12     33         resign   
7      RVN0N3VK  False  1.503680e+12  1.503680e+12      9         resign   
8      dwF3DJHO   True  1.503510e+12  1.503510e+12     66         resign   
...         ...    ...           ...           ...    ...            ...   
20053  EfqH7VVH   True  1.499791e+12  1.499791e+12     24         resign   
20054  WSJDhbPl   True  1.499698e+12  1.499699e+12     82           mate   
20055  yrAas0Kj   True  1.499698e+12  1.499698e+12     35           mate   
20056  b0v4tRyF   True  1.499696e+12  1.499697e+12    109         resign   
20057  N8G2JHGG   True  1.499643e+12  1.499644e+12     78           mate   

      winner increment_code            white_id  white_rating  \
0      white           15+2            bourgris          1500   
5       draw           10+0           trelynn17          1250   
6      white           10+0             capa_jr          1520   
7      black          15+30  daniel_likes_chess          1413   
8      black           15+0           ehabfanri          1439   
...      ...            ...                 ...           ...   
20053  white          10+10             belcolt          1691   
20054  black           10+0            jamboger          1233   
20055  white           10+0            jamboger          1219   
20056  white           10+0        marcodisogno          1360   
20057  black           10+0            jamboger          1235   

                 black_id  black_rating  \
0                    a-00          1191   
5           franklin14532          1002   
6      daniel_likes_chess          1423   
7                soultego          2108   
8      daniel_likes_chess          1392   
...                   ...           ...   
20053            jamboger          1220   
20054  farrukhasomiddinov          1196   
20055        schaaksmurf3          1286   
20056            jamboger          1227   
20057               ffbob          1339   

                                                   moves opening_eco  \
0      d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...         D10   
5                                       e4 c5 Nf3 Qa5 a3         B27   
6      d4 d5 e4 dxe4 Nc3 Nf6 f3 exf3 Nxf3 Nc6 Bb5 a6 ...         D00   
7                         e4 Nc6 d4 e5 d5 Nce7 c3 Ng6 b4         B00   
8      e4 e5 Bc4 Nc6 Nf3 Nd4 d3 Nxf3+ Qxf3 Nf6 h3 Bc5...         C50   
...                                                  ...         ...   
20053  d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...         A80   
20054  d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...         A41   
20055  d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...         D00   
20056  e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...         B07   
20057  d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...         D00   

                                            opening_name  opening_ply  
0                       Slav Defense: Exchange Variation            5  
5                   Sicilian Defense: Mongoose Variation            4  
6             Blackmar-Diemer Gambit: Pietrowsky Defense           10  
7      Nimzowitsch Defense: Kennedy Variation |  Link...            5  
8                  Italian Game: Schilling-Kostic Gambit            6  
...                                                  ...          ...  
20053                                      Dutch Defense            2  
20054                                       Queen's Pawn            2  
20055                    Queen's Pawn Game: Mason Attack            3  
20056                                       Pirc Defense            4  
20057                    Queen's Pawn Game: Mason Attack            3  

[20054 rows x 16 columns]

Пункт 6.Удаление ненужных столбцов или строчек.Удаляем ненужные строчки из таблицы под номерами 1,2,3,4.

In [52]:
games = games.replace({"turns":13}, 18) 
games

id  rated    created_at  last_move_at  turns victory_status  \
0      TZJHLljE  False  1.504210e+12  1.504210e+12     18      outoftime   
5      MsoDV9wj  False  1.504240e+12  1.504240e+12      5           draw   
6      qwU9rasv   True  1.504230e+12  1.504230e+12     33         resign   
7      RVN0N3VK  False  1.503680e+12  1.503680e+12      9         resign   
8      dwF3DJHO   True  1.503510e+12  1.503510e+12     66         resign   
...         ...    ...           ...           ...    ...            ...   
20053  EfqH7VVH   True  1.499791e+12  1.499791e+12     24         resign   
20054  WSJDhbPl   True  1.499698e+12  1.499699e+12     82           mate   
20055  yrAas0Kj   True  1.499698e+12  1.499698e+12     35           mate   
20056  b0v4tRyF   True  1.499696e+12  1.499697e+12    109         resign   
20057  N8G2JHGG   True  1.499643e+12  1.499644e+12     78           mate   

      winner increment_code            white_id  white_rating  \
0      white           15+2            bourgris          1500   
5       draw           10+0           trelynn17          1250   
6      white           10+0             capa_jr          1520   
7      black          15+30  daniel_likes_chess          1413   
8      black           15+0           ehabfanri          1439   
...      ...            ...                 ...           ...   
20053  white          10+10             belcolt          1691   
20054  black           10+0            jamboger          1233   
20055  white           10+0            jamboger          1219   
20056  white           10+0        marcodisogno          1360   
20057  black           10+0            jamboger          1235   

                 black_id  black_rating  \
0                    a-00          1191   
5           franklin14532          1002   
6      daniel_likes_chess          1423   
7                soultego          2108   
8      daniel_likes_chess          1392   
...                   ...           ...   
20053            jamboger          1220   
20054  farrukhasomiddinov          1196   
20055        schaaksmurf3          1286   
20056            jamboger          1227   
20057               ffbob          1339   

                                                   moves opening_eco  \
0      d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...         D10   
5                                       e4 c5 Nf3 Qa5 a3         B27   
6      d4 d5 e4 dxe4 Nc3 Nf6 f3 exf3 Nxf3 Nc6 Bb5 a6 ...         D00   
7                         e4 Nc6 d4 e5 d5 Nce7 c3 Ng6 b4         B00   
8      e4 e5 Bc4 Nc6 Nf3 Nd4 d3 Nxf3+ Qxf3 Nf6 h3 Bc5...         C50   
...                                                  ...         ...   
20053  d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...         A80   
20054  d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...         A41   
20055  d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...         D00   
20056  e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...         B07   
20057  d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...         D00   

                                            opening_name  opening_ply  
0                       Slav Defense: Exchange Variation            5  
5                   Sicilian Defense: Mongoose Variation            4  
6             Blackmar-Diemer Gambit: Pietrowsky Defense           10  
7      Nimzowitsch Defense: Kennedy Variation |  Link...            5  
8                  Italian Game: Schilling-Kostic Gambit            6  
...                                                  ...          ...  
20053                                      Dutch Defense            2  
20054                                       Queen's Pawn            2  
20055                    Queen's Pawn Game: Mason Attack            3  
20056                                       Pirc Defense            4  
20057                    Queen's Pawn Game: Mason Attack            3  

[20054 rows x 16 columns]

Пункт 7.Заменить определенные значения в датасете (например, пустые). В столбце "turns" занчение 13 заменяется на 18.

In [47]:
games.drop_duplicates()

id  rated    created_at  last_move_at  turns victory_status  \
0      TZJHLljE  False  1.504210e+12  1.504210e+12     13      outoftime   
5      MsoDV9wj  False  1.504240e+12  1.504240e+12      5           draw   
6      qwU9rasv   True  1.504230e+12  1.504230e+12     33         resign   
7      RVN0N3VK  False  1.503680e+12  1.503680e+12      9         resign   
8      dwF3DJHO   True  1.503510e+12  1.503510e+12     66         resign   
...         ...    ...           ...           ...    ...            ...   
20053  EfqH7VVH   True  1.499791e+12  1.499791e+12     24         resign   
20054  WSJDhbPl   True  1.499698e+12  1.499699e+12     82           mate   
20055  yrAas0Kj   True  1.499698e+12  1.499698e+12     35           mate   
20056  b0v4tRyF   True  1.499696e+12  1.499697e+12    109         resign   
20057  N8G2JHGG   True  1.499643e+12  1.499644e+12     78           mate   

      winner increment_code            white_id  white_rating  \
0      white           15+2            bourgris          1500   
5       draw           10+0           trelynn17          1250   
6      white           10+0             capa_jr          1520   
7      black          15+30  daniel_likes_chess          1413   
8      black           15+0           ehabfanri          1439   
...      ...            ...                 ...           ...   
20053  white          10+10             belcolt          1691   
20054  black           10+0            jamboger          1233   
20055  white           10+0            jamboger          1219   
20056  white           10+0        marcodisogno          1360   
20057  black           10+0            jamboger          1235   

                 black_id  black_rating  \
0                    a-00          1191   
5           franklin14532          1002   
6      daniel_likes_chess          1423   
7                soultego          2108   
8      daniel_likes_chess          1392   
...                   ...           ...   
20053            jamboger          1220   
20054  farrukhasomiddinov          1196   
20055        schaaksmurf3          1286   
20056            jamboger          1227   
20057               ffbob          1339   

                                                   moves opening_eco  \
0      d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...         D10   
5                                       e4 c5 Nf3 Qa5 a3         B27   
6      d4 d5 e4 dxe4 Nc3 Nf6 f3 exf3 Nxf3 Nc6 Bb5 a6 ...         D00   
7                         e4 Nc6 d4 e5 d5 Nce7 c3 Ng6 b4         B00   
8      e4 e5 Bc4 Nc6 Nf3 Nd4 d3 Nxf3+ Qxf3 Nf6 h3 Bc5...         C50   
...                                                  ...         ...   
20053  d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...         A80   
20054  d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...         A41   
20055  d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...         D00   
20056  e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...         B07   
20057  d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...         D00   

                                            opening_name  opening_ply  
0                       Slav Defense: Exchange Variation            5  
5                   Sicilian Defense: Mongoose Variation            4  
6             Blackmar-Diemer Gambit: Pietrowsky Defense           10  
7      Nimzowitsch Defense: Kennedy Variation |  Link...            5  
8                  Italian Game: Schilling-Kostic Gambit            6  
...                                                  ...          ...  
20053                                      Dutch Defense            2  
20054                                       Queen's Pawn            2  
20055                    Queen's Pawn Game: Mason Attack            3  
20056                                       Pirc Defense            4  
20057                    Queen's Pawn Game: Mason Attack            3  

[19625 rows x 16 columns]

Пункт 8.Удалеие дубликатов из датасета.

In [48]:
games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20054 entries, 0 to 20057
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              20054 non-null  object 
 1   rated           20054 non-null  bool   
 2   created_at      20054 non-null  float64
 3   last_move_at    20054 non-null  float64
 4   turns           20054 non-null  int64  
 5   victory_status  20054 non-null  object 
 6   winner          20054 non-null  object 
 7   increment_code  20054 non-null  object 
 8   white_id        20054 non-null  object 
 9   white_rating    20054 non-null  int64  
 10  black_id        20054 non-null  object 
 11  black_rating    20054 non-null  int64  
 12  moves           20054 non-null  object 
 13  opening_eco     20054 non-null  object 
 14  opening_name    20054 non-null  object 
 15  opening_ply     20054 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(9)
memory usage: 2.5+ MB


Пункт 9.Провести анализ с помощью функций info.В данном датасете существует 4 значения типа int, 2 float, 1 bool, 4 object. При выводе описано 16 колонок и 200057 строк.

In [49]:
games.describe()

created_at  last_move_at         turns  white_rating  black_rating  \
count  2.005400e+04  2.005400e+04  20054.000000  20054.000000  20054.000000   
mean   1.483613e+12  1.483614e+12     60.466441   1596.662112   1588.865463   
std    2.850288e+10  2.850277e+10     33.571578    291.272507    291.052479   
min    1.376772e+12  1.376772e+12      1.000000    784.000000    789.000000   
25%    1.477536e+12  1.477540e+12     37.000000   1398.000000   1391.000000   
50%    1.496001e+12  1.496002e+12     55.000000   1567.000000   1562.000000   
75%    1.503170e+12  1.503170e+12     79.000000   1793.000000   1784.000000   
max    1.504493e+12  1.504494e+12    349.000000   2700.000000   2723.000000   

        opening_ply  
count  20054.000000  
mean       4.817194  
std        2.797366  
min        1.000000  
25%        3.000000  
50%        4.000000  
75%        6.000000  
max       28.000000

Пункт 10.Провести анализ с помощью функций describe.Который вывел для каждого столбца свои статические показатели,к примеру, видно, что максимальное значение в столбце  turns = 349.000000, а минимальное 1.000000.

In [51]:
subset = games.loc[[10,11,12,13], ['id','rated','turns']]
subset

id  rated  turns
10  HgKLWPsz  False     39
11  Vf5fKWzI  False     38
12  HRti5mKv  False     60
13  2fEjSei6  False     31

Пункт 11.Провести выборку данных по строкам и столбцам с помощью loc. Были выбраны столбцы под названиями id	rated	turns , и строки 10,11,12,13.

In [53]:
games.to_csv("chess_clear.csv")

Пункт 12.Сохранить новый датасет под названием chess.

Вывод:  в ходе работы были полкчены навыки работы с датасетами.А так же реализован базовый анализ датасета. Выведен весь датасет и описан.Выведена размерноть массива.Выведено наименование всех колонок, описано, что они означают.Выведены все уникальные значения. Отсортированы по определенным параметрам. Удалины ненужные столбцы или строчки. Заменены определенные значения в датасете.Удалены дубликаты.Проведен анализ с помощью функций info.Проведен анализ с помощью функций describe.Проведена выборка данных по строкам и столбцам с помощью loc.